CREATE DATABASE DB_PETSHOP;
USE DB_PETSHOP;

CREATE TABLE TB_PERFIS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(20) NOT NULL
);

CREATE TABLE TB_USUARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    SENHA VARCHAR(64) NOT NULL,
    FOTO VARCHAR(255),
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S','N')),
    PERFIL_ID INT,
    FOREIGN KEY (PERFIL_ID) REFERENCES TB_PERFIS(ID)
);

CREATE TABLE TB_FUNCIONARIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    ENDERECO VARCHAR(50),
    BAIRRO VARCHAR(30),
    CIDADE VARCHAR(50),
    UF VARCHAR(2),
    CEP VARCHAR(9) NOT NULL,
    TELEFONE VARCHAR(15),
    CARGO VARCHAR(20),
    SALARIO DECIMAL(7,2) NOT NULL,
    USUARIO_ID INT,
    FOREIGN KEY (USUARIO_ID) REFERENCES TB_USUARIOS(ID)
);

CREATE TABLE TB_TUTORES (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    ENDERECO VARCHAR(50),
    BAIRRO VARCHAR(30),
    CIDADE VARCHAR(50),
    UF VARCHAR(2),
    CEP VARCHAR(9) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    USUARIO_ID INT,
    FOREIGN KEY (USUARIO_ID) REFERENCES TB_USUARIOS(ID)
);

CREATE TABLE TB_PETS (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    RACA VARCHAR(30) NOT NULL,
    DT_NASCIMENTO DATE,
    TAMANHO INT NOT NULL CHECK (TAMANHO IN (1,2,3,4)),
    PESO DECIMAL(5,2) NOT NULL,
    OBS TEXT,
    OCORRENCIAS TEXT,
    TUTOR_ID INT,
    FOREIGN KEY (TUTOR_ID) REFERENCES TB_TUTORES (ID)
);

CREATE TABLE TB_SERVICOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(50) NOT NULL,
    VALOR DECIMAL(7,2) NOT NULL
);

CREATE TABLE TB_AGENDAMENTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DT_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP(),
    DT_AGENDAMENTO DATETIME NOT NULL,
    DESCRICAO TEXT,
    OBS TEXT,
    STATUS VARCHAR(20) DEFAULT 'AGENDADO',
    SERVICO_ID INT,
    FUNC_ID INT,
    CRIADOR_ID INT,
    PET_ID INT,
    FOREIGN KEY (SERVICO_ID) REFERENCES TB_SERVICOS(ID),
    FOREIGN KEY (FUNC_ID) REFERENCES TB_FUNCIONARIOS(ID),
    FOREIGN KEY (CRIADOR_ID) REFERENCES TB_USUARIOS(ID),
    FOREIGN KEY (PET_ID) REFERENCES TB_PETS(ID)
);

-- Inserts de dados iniciais
INSERT INTO TB_PERFIS (DESCRICAO) VALUES ('Administrador'), ('Tutor'), ('Funcionario');
INSERT INTO TB_USUARIOS (EMAIL, SENHA, ATIVO, PERFIL_ID) VALUES ('admin', 'admin', 'S', 1);
INSERT INTO TB_USUARIOS (EMAIL, SENHA, ATIVO, PERFIL_ID) VALUES ('cli', 'cli', 'S', 2);

-- Inserindo os serviços padrão
INSERT INTO TB_SERVICOS (DESCRICAO, VALOR) VALUES
('Banho', 50.00),
('Tosa', 70.00),
('Banho e Tosa', 110.00),
('Consulta Médica', 150.00);